name: "BUG 🐛🔥"
description: "Bug firx"
title: "[🐛 BUG] "
labels: ["🐛 BUG", "📙 NOT READ"]

body:
  - type: markdown
    attributes:
      value: "Markdown"
  - type: markdown
    attributes:
      value: "the markdown for bug"

  - type: checkboxes
    id: "checks"
    attributes:
      label: "Is everything done"
      options:
      - label: "Is issue (https://github.com/peterhvw/monorepo-example/issue) done. 🙆🏻"
        required: true
      - label: "is tested (https://github.com/peterhvw/monorepo-example/issuee)?"
        required: true
      - label: "Did you have approve! 😖"
        required: false

  - type: dropdown
    attributes:
      label: "Onder welke categorie valt het"
      multiple: true
      options:
        - 'Web'
        - 'Admin'
        - 'Storybook'
        - 'Build'
        - 'CI/CD'
        - 'API'
        - '3rd party libraries'
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🎬 extra bug info
      description: "Extra bug infor"
      placeholder: |
        1. hierdoor.
        2. dit gedaan.
        3. volledig opgelost.
    validations:
      required: true
