name: "FEATURE REQUEST 💌🎁"
description: "New feature request"
title: "[💌 FEATURE REQUEST] "
labels: ["📙 NOT READ"]

body:
- type: markdown
  attributes:
    value: "Markdown text updated"
- type: markdown
  attributes:
    value: "Markdown text updated"

- type: checkboxes
  id: "checks"
  attributes:
    label: "new checkboxes"
    options:
    - label: "label 1 dod"
      required: true
    - label: "label 2 tested"
      required: false
    
- type: textarea
  id: "description"
  attributes:
    label: "Text area"
    description: "describing Text area"
  validations:
    required: true

- type: textarea
  id: "expected-result"
  attributes:
    label: "result"
    description: "What is the expected result?"
    placeholder: "example"
  validations:
    required: true

- type: textarea
  id: "alternative"
  attributes:
    label: "Alternative"
    description: "What would be an alternative?"
    placeholder: |
      "List of options"
      "1. Option 1."
      "2. Option 2."
  validations:
    required: false

- type: textarea
  id: "reference"
  attributes:
    label: "reference jira"
    description: "Should give a reference from jira 🙇🏻‍♂️🙇‍♀️"
  validations:
    required: false